// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: menu.proto

package role;

public final class MenuOuterClass {
  private MenuOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:role.Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();
  }
  /**
   * <pre>
   * The request message containing the user's name.
   * </pre>
   *
   * Protobuf type {@code role.Request}
   */
  public  static final class Request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:role.Request)
      RequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Request() {
      id_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return role.MenuOuterClass.internal_static_role_Request_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return role.MenuOuterClass.internal_static_role_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              role.MenuOuterClass.Request.class, role.MenuOuterClass.Request.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof role.MenuOuterClass.Request)) {
        return super.equals(obj);
      }
      role.MenuOuterClass.Request other = (role.MenuOuterClass.Request) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static role.MenuOuterClass.Request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static role.MenuOuterClass.Request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static role.MenuOuterClass.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static role.MenuOuterClass.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static role.MenuOuterClass.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static role.MenuOuterClass.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static role.MenuOuterClass.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static role.MenuOuterClass.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static role.MenuOuterClass.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static role.MenuOuterClass.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static role.MenuOuterClass.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static role.MenuOuterClass.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(role.MenuOuterClass.Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * The request message containing the user's name.
     * </pre>
     *
     * Protobuf type {@code role.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:role.Request)
        role.MenuOuterClass.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return role.MenuOuterClass.internal_static_role_Request_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return role.MenuOuterClass.internal_static_role_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                role.MenuOuterClass.Request.class, role.MenuOuterClass.Request.Builder.class);
      }

      // Construct using role.MenuOuterClass.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return role.MenuOuterClass.internal_static_role_Request_descriptor;
      }

      @java.lang.Override
      public role.MenuOuterClass.Request getDefaultInstanceForType() {
        return role.MenuOuterClass.Request.getDefaultInstance();
      }

      @java.lang.Override
      public role.MenuOuterClass.Request build() {
        role.MenuOuterClass.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public role.MenuOuterClass.Request buildPartial() {
        role.MenuOuterClass.Request result = new role.MenuOuterClass.Request(this);
        result.id_ = id_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof role.MenuOuterClass.Request) {
          return mergeFrom((role.MenuOuterClass.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(role.MenuOuterClass.Request other) {
        if (other == role.MenuOuterClass.Request.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        role.MenuOuterClass.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (role.MenuOuterClass.Request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:role.Request)
    }

    // @@protoc_insertion_point(class_scope:role.Request)
    private static final role.MenuOuterClass.Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new role.MenuOuterClass.Request();
    }

    public static role.MenuOuterClass.Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Request>
        PARSER = new com.google.protobuf.AbstractParser<Request>() {
      @java.lang.Override
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public role.MenuOuterClass.Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:role.Reply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>.role.MenuItem menuItem = 5;</code>
     */
    boolean hasMenuItem();
    /**
     * <code>.role.MenuItem menuItem = 5;</code>
     */
    role.MenuOuterClass.MenuItem getMenuItem();
    /**
     * <code>.role.MenuItem menuItem = 5;</code>
     */
    role.MenuOuterClass.MenuItemOrBuilder getMenuItemOrBuilder();
  }
  /**
   * <pre>
   * The response message containing the greetings
   * </pre>
   *
   * Protobuf type {@code role.Reply}
   */
  public  static final class Reply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:role.Reply)
      ReplyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Reply.newBuilder() to construct.
    private Reply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Reply() {
      id_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Reply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 42: {
              role.MenuOuterClass.MenuItem.Builder subBuilder = null;
              if (menuItem_ != null) {
                subBuilder = menuItem_.toBuilder();
              }
              menuItem_ = input.readMessage(role.MenuOuterClass.MenuItem.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(menuItem_);
                menuItem_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return role.MenuOuterClass.internal_static_role_Reply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return role.MenuOuterClass.internal_static_role_Reply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              role.MenuOuterClass.Reply.class, role.MenuOuterClass.Reply.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MENUITEM_FIELD_NUMBER = 5;
    private role.MenuOuterClass.MenuItem menuItem_;
    /**
     * <code>.role.MenuItem menuItem = 5;</code>
     */
    public boolean hasMenuItem() {
      return menuItem_ != null;
    }
    /**
     * <code>.role.MenuItem menuItem = 5;</code>
     */
    public role.MenuOuterClass.MenuItem getMenuItem() {
      return menuItem_ == null ? role.MenuOuterClass.MenuItem.getDefaultInstance() : menuItem_;
    }
    /**
     * <code>.role.MenuItem menuItem = 5;</code>
     */
    public role.MenuOuterClass.MenuItemOrBuilder getMenuItemOrBuilder() {
      return getMenuItem();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (menuItem_ != null) {
        output.writeMessage(5, getMenuItem());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (menuItem_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getMenuItem());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof role.MenuOuterClass.Reply)) {
        return super.equals(obj);
      }
      role.MenuOuterClass.Reply other = (role.MenuOuterClass.Reply) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (hasMenuItem() != other.hasMenuItem()) return false;
      if (hasMenuItem()) {
        if (!getMenuItem()
            .equals(other.getMenuItem())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      if (hasMenuItem()) {
        hash = (37 * hash) + MENUITEM_FIELD_NUMBER;
        hash = (53 * hash) + getMenuItem().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static role.MenuOuterClass.Reply parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static role.MenuOuterClass.Reply parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static role.MenuOuterClass.Reply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static role.MenuOuterClass.Reply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static role.MenuOuterClass.Reply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static role.MenuOuterClass.Reply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static role.MenuOuterClass.Reply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static role.MenuOuterClass.Reply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static role.MenuOuterClass.Reply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static role.MenuOuterClass.Reply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static role.MenuOuterClass.Reply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static role.MenuOuterClass.Reply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(role.MenuOuterClass.Reply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * The response message containing the greetings
     * </pre>
     *
     * Protobuf type {@code role.Reply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:role.Reply)
        role.MenuOuterClass.ReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return role.MenuOuterClass.internal_static_role_Reply_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return role.MenuOuterClass.internal_static_role_Reply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                role.MenuOuterClass.Reply.class, role.MenuOuterClass.Reply.Builder.class);
      }

      // Construct using role.MenuOuterClass.Reply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        if (menuItemBuilder_ == null) {
          menuItem_ = null;
        } else {
          menuItem_ = null;
          menuItemBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return role.MenuOuterClass.internal_static_role_Reply_descriptor;
      }

      @java.lang.Override
      public role.MenuOuterClass.Reply getDefaultInstanceForType() {
        return role.MenuOuterClass.Reply.getDefaultInstance();
      }

      @java.lang.Override
      public role.MenuOuterClass.Reply build() {
        role.MenuOuterClass.Reply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public role.MenuOuterClass.Reply buildPartial() {
        role.MenuOuterClass.Reply result = new role.MenuOuterClass.Reply(this);
        result.id_ = id_;
        if (menuItemBuilder_ == null) {
          result.menuItem_ = menuItem_;
        } else {
          result.menuItem_ = menuItemBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof role.MenuOuterClass.Reply) {
          return mergeFrom((role.MenuOuterClass.Reply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(role.MenuOuterClass.Reply other) {
        if (other == role.MenuOuterClass.Reply.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (other.hasMenuItem()) {
          mergeMenuItem(other.getMenuItem());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        role.MenuOuterClass.Reply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (role.MenuOuterClass.Reply) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private role.MenuOuterClass.MenuItem menuItem_;
      private com.google.protobuf.SingleFieldBuilderV3<
          role.MenuOuterClass.MenuItem, role.MenuOuterClass.MenuItem.Builder, role.MenuOuterClass.MenuItemOrBuilder> menuItemBuilder_;
      /**
       * <code>.role.MenuItem menuItem = 5;</code>
       */
      public boolean hasMenuItem() {
        return menuItemBuilder_ != null || menuItem_ != null;
      }
      /**
       * <code>.role.MenuItem menuItem = 5;</code>
       */
      public role.MenuOuterClass.MenuItem getMenuItem() {
        if (menuItemBuilder_ == null) {
          return menuItem_ == null ? role.MenuOuterClass.MenuItem.getDefaultInstance() : menuItem_;
        } else {
          return menuItemBuilder_.getMessage();
        }
      }
      /**
       * <code>.role.MenuItem menuItem = 5;</code>
       */
      public Builder setMenuItem(role.MenuOuterClass.MenuItem value) {
        if (menuItemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          menuItem_ = value;
          onChanged();
        } else {
          menuItemBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.role.MenuItem menuItem = 5;</code>
       */
      public Builder setMenuItem(
          role.MenuOuterClass.MenuItem.Builder builderForValue) {
        if (menuItemBuilder_ == null) {
          menuItem_ = builderForValue.build();
          onChanged();
        } else {
          menuItemBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.role.MenuItem menuItem = 5;</code>
       */
      public Builder mergeMenuItem(role.MenuOuterClass.MenuItem value) {
        if (menuItemBuilder_ == null) {
          if (menuItem_ != null) {
            menuItem_ =
              role.MenuOuterClass.MenuItem.newBuilder(menuItem_).mergeFrom(value).buildPartial();
          } else {
            menuItem_ = value;
          }
          onChanged();
        } else {
          menuItemBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.role.MenuItem menuItem = 5;</code>
       */
      public Builder clearMenuItem() {
        if (menuItemBuilder_ == null) {
          menuItem_ = null;
          onChanged();
        } else {
          menuItem_ = null;
          menuItemBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.role.MenuItem menuItem = 5;</code>
       */
      public role.MenuOuterClass.MenuItem.Builder getMenuItemBuilder() {
        
        onChanged();
        return getMenuItemFieldBuilder().getBuilder();
      }
      /**
       * <code>.role.MenuItem menuItem = 5;</code>
       */
      public role.MenuOuterClass.MenuItemOrBuilder getMenuItemOrBuilder() {
        if (menuItemBuilder_ != null) {
          return menuItemBuilder_.getMessageOrBuilder();
        } else {
          return menuItem_ == null ?
              role.MenuOuterClass.MenuItem.getDefaultInstance() : menuItem_;
        }
      }
      /**
       * <code>.role.MenuItem menuItem = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          role.MenuOuterClass.MenuItem, role.MenuOuterClass.MenuItem.Builder, role.MenuOuterClass.MenuItemOrBuilder> 
          getMenuItemFieldBuilder() {
        if (menuItemBuilder_ == null) {
          menuItemBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              role.MenuOuterClass.MenuItem, role.MenuOuterClass.MenuItem.Builder, role.MenuOuterClass.MenuItemOrBuilder>(
                  getMenuItem(),
                  getParentForChildren(),
                  isClean());
          menuItem_ = null;
        }
        return menuItemBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:role.Reply)
    }

    // @@protoc_insertion_point(class_scope:role.Reply)
    private static final role.MenuOuterClass.Reply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new role.MenuOuterClass.Reply();
    }

    public static role.MenuOuterClass.Reply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Reply>
        PARSER = new com.google.protobuf.AbstractParser<Reply>() {
      @java.lang.Override
      public Reply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Reply(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Reply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Reply> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public role.MenuOuterClass.Reply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MenuItemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:role.MenuItem)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string menuparent = 1;</code>
     */
    java.lang.String getMenuparent();
    /**
     * <code>string menuparent = 1;</code>
     */
    com.google.protobuf.ByteString
        getMenuparentBytes();

    /**
     * <code>string menuname = 2;</code>
     */
    java.lang.String getMenuname();
    /**
     * <code>string menuname = 2;</code>
     */
    com.google.protobuf.ByteString
        getMenunameBytes();

    /**
     * <code>string menucode = 3;</code>
     */
    java.lang.String getMenucode();
    /**
     * <code>string menucode = 3;</code>
     */
    com.google.protobuf.ByteString
        getMenucodeBytes();

    /**
     * <code>string seq = 4;</code>
     */
    java.lang.String getSeq();
    /**
     * <code>string seq = 4;</code>
     */
    com.google.protobuf.ByteString
        getSeqBytes();

    /**
     * <code>repeated .role.MenuItem menuchild = 5;</code>
     */
    java.util.List<role.MenuOuterClass.MenuItem> 
        getMenuchildList();
    /**
     * <code>repeated .role.MenuItem menuchild = 5;</code>
     */
    role.MenuOuterClass.MenuItem getMenuchild(int index);
    /**
     * <code>repeated .role.MenuItem menuchild = 5;</code>
     */
    int getMenuchildCount();
    /**
     * <code>repeated .role.MenuItem menuchild = 5;</code>
     */
    java.util.List<? extends role.MenuOuterClass.MenuItemOrBuilder> 
        getMenuchildOrBuilderList();
    /**
     * <code>repeated .role.MenuItem menuchild = 5;</code>
     */
    role.MenuOuterClass.MenuItemOrBuilder getMenuchildOrBuilder(
        int index);
  }
  /**
   * <pre>
   * The request message containing the user's name.
   * </pre>
   *
   * Protobuf type {@code role.MenuItem}
   */
  public  static final class MenuItem extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:role.MenuItem)
      MenuItemOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MenuItem.newBuilder() to construct.
    private MenuItem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MenuItem() {
      menuparent_ = "";
      menuname_ = "";
      menucode_ = "";
      seq_ = "";
      menuchild_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MenuItem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              menuparent_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              menuname_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              menucode_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              seq_ = s;
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) != 0)) {
                menuchild_ = new java.util.ArrayList<role.MenuOuterClass.MenuItem>();
                mutable_bitField0_ |= 0x00000010;
              }
              menuchild_.add(
                  input.readMessage(role.MenuOuterClass.MenuItem.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) != 0)) {
          menuchild_ = java.util.Collections.unmodifiableList(menuchild_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return role.MenuOuterClass.internal_static_role_MenuItem_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return role.MenuOuterClass.internal_static_role_MenuItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              role.MenuOuterClass.MenuItem.class, role.MenuOuterClass.MenuItem.Builder.class);
    }

    private int bitField0_;
    public static final int MENUPARENT_FIELD_NUMBER = 1;
    private volatile java.lang.Object menuparent_;
    /**
     * <code>string menuparent = 1;</code>
     */
    public java.lang.String getMenuparent() {
      java.lang.Object ref = menuparent_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        menuparent_ = s;
        return s;
      }
    }
    /**
     * <code>string menuparent = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMenuparentBytes() {
      java.lang.Object ref = menuparent_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        menuparent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MENUNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object menuname_;
    /**
     * <code>string menuname = 2;</code>
     */
    public java.lang.String getMenuname() {
      java.lang.Object ref = menuname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        menuname_ = s;
        return s;
      }
    }
    /**
     * <code>string menuname = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMenunameBytes() {
      java.lang.Object ref = menuname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        menuname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MENUCODE_FIELD_NUMBER = 3;
    private volatile java.lang.Object menucode_;
    /**
     * <code>string menucode = 3;</code>
     */
    public java.lang.String getMenucode() {
      java.lang.Object ref = menucode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        menucode_ = s;
        return s;
      }
    }
    /**
     * <code>string menucode = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMenucodeBytes() {
      java.lang.Object ref = menucode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        menucode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEQ_FIELD_NUMBER = 4;
    private volatile java.lang.Object seq_;
    /**
     * <code>string seq = 4;</code>
     */
    public java.lang.String getSeq() {
      java.lang.Object ref = seq_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        seq_ = s;
        return s;
      }
    }
    /**
     * <code>string seq = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSeqBytes() {
      java.lang.Object ref = seq_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        seq_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MENUCHILD_FIELD_NUMBER = 5;
    private java.util.List<role.MenuOuterClass.MenuItem> menuchild_;
    /**
     * <code>repeated .role.MenuItem menuchild = 5;</code>
     */
    public java.util.List<role.MenuOuterClass.MenuItem> getMenuchildList() {
      return menuchild_;
    }
    /**
     * <code>repeated .role.MenuItem menuchild = 5;</code>
     */
    public java.util.List<? extends role.MenuOuterClass.MenuItemOrBuilder> 
        getMenuchildOrBuilderList() {
      return menuchild_;
    }
    /**
     * <code>repeated .role.MenuItem menuchild = 5;</code>
     */
    public int getMenuchildCount() {
      return menuchild_.size();
    }
    /**
     * <code>repeated .role.MenuItem menuchild = 5;</code>
     */
    public role.MenuOuterClass.MenuItem getMenuchild(int index) {
      return menuchild_.get(index);
    }
    /**
     * <code>repeated .role.MenuItem menuchild = 5;</code>
     */
    public role.MenuOuterClass.MenuItemOrBuilder getMenuchildOrBuilder(
        int index) {
      return menuchild_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMenuparentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, menuparent_);
      }
      if (!getMenunameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, menuname_);
      }
      if (!getMenucodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, menucode_);
      }
      if (!getSeqBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, seq_);
      }
      for (int i = 0; i < menuchild_.size(); i++) {
        output.writeMessage(5, menuchild_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMenuparentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, menuparent_);
      }
      if (!getMenunameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, menuname_);
      }
      if (!getMenucodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, menucode_);
      }
      if (!getSeqBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, seq_);
      }
      for (int i = 0; i < menuchild_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, menuchild_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof role.MenuOuterClass.MenuItem)) {
        return super.equals(obj);
      }
      role.MenuOuterClass.MenuItem other = (role.MenuOuterClass.MenuItem) obj;

      if (!getMenuparent()
          .equals(other.getMenuparent())) return false;
      if (!getMenuname()
          .equals(other.getMenuname())) return false;
      if (!getMenucode()
          .equals(other.getMenucode())) return false;
      if (!getSeq()
          .equals(other.getSeq())) return false;
      if (!getMenuchildList()
          .equals(other.getMenuchildList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MENUPARENT_FIELD_NUMBER;
      hash = (53 * hash) + getMenuparent().hashCode();
      hash = (37 * hash) + MENUNAME_FIELD_NUMBER;
      hash = (53 * hash) + getMenuname().hashCode();
      hash = (37 * hash) + MENUCODE_FIELD_NUMBER;
      hash = (53 * hash) + getMenucode().hashCode();
      hash = (37 * hash) + SEQ_FIELD_NUMBER;
      hash = (53 * hash) + getSeq().hashCode();
      if (getMenuchildCount() > 0) {
        hash = (37 * hash) + MENUCHILD_FIELD_NUMBER;
        hash = (53 * hash) + getMenuchildList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static role.MenuOuterClass.MenuItem parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static role.MenuOuterClass.MenuItem parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static role.MenuOuterClass.MenuItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static role.MenuOuterClass.MenuItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static role.MenuOuterClass.MenuItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static role.MenuOuterClass.MenuItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static role.MenuOuterClass.MenuItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static role.MenuOuterClass.MenuItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static role.MenuOuterClass.MenuItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static role.MenuOuterClass.MenuItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static role.MenuOuterClass.MenuItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static role.MenuOuterClass.MenuItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(role.MenuOuterClass.MenuItem prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * The request message containing the user's name.
     * </pre>
     *
     * Protobuf type {@code role.MenuItem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:role.MenuItem)
        role.MenuOuterClass.MenuItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return role.MenuOuterClass.internal_static_role_MenuItem_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return role.MenuOuterClass.internal_static_role_MenuItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                role.MenuOuterClass.MenuItem.class, role.MenuOuterClass.MenuItem.Builder.class);
      }

      // Construct using role.MenuOuterClass.MenuItem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMenuchildFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        menuparent_ = "";

        menuname_ = "";

        menucode_ = "";

        seq_ = "";

        if (menuchildBuilder_ == null) {
          menuchild_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          menuchildBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return role.MenuOuterClass.internal_static_role_MenuItem_descriptor;
      }

      @java.lang.Override
      public role.MenuOuterClass.MenuItem getDefaultInstanceForType() {
        return role.MenuOuterClass.MenuItem.getDefaultInstance();
      }

      @java.lang.Override
      public role.MenuOuterClass.MenuItem build() {
        role.MenuOuterClass.MenuItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public role.MenuOuterClass.MenuItem buildPartial() {
        role.MenuOuterClass.MenuItem result = new role.MenuOuterClass.MenuItem(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.menuparent_ = menuparent_;
        result.menuname_ = menuname_;
        result.menucode_ = menucode_;
        result.seq_ = seq_;
        if (menuchildBuilder_ == null) {
          if (((bitField0_ & 0x00000010) != 0)) {
            menuchild_ = java.util.Collections.unmodifiableList(menuchild_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.menuchild_ = menuchild_;
        } else {
          result.menuchild_ = menuchildBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof role.MenuOuterClass.MenuItem) {
          return mergeFrom((role.MenuOuterClass.MenuItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(role.MenuOuterClass.MenuItem other) {
        if (other == role.MenuOuterClass.MenuItem.getDefaultInstance()) return this;
        if (!other.getMenuparent().isEmpty()) {
          menuparent_ = other.menuparent_;
          onChanged();
        }
        if (!other.getMenuname().isEmpty()) {
          menuname_ = other.menuname_;
          onChanged();
        }
        if (!other.getMenucode().isEmpty()) {
          menucode_ = other.menucode_;
          onChanged();
        }
        if (!other.getSeq().isEmpty()) {
          seq_ = other.seq_;
          onChanged();
        }
        if (menuchildBuilder_ == null) {
          if (!other.menuchild_.isEmpty()) {
            if (menuchild_.isEmpty()) {
              menuchild_ = other.menuchild_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureMenuchildIsMutable();
              menuchild_.addAll(other.menuchild_);
            }
            onChanged();
          }
        } else {
          if (!other.menuchild_.isEmpty()) {
            if (menuchildBuilder_.isEmpty()) {
              menuchildBuilder_.dispose();
              menuchildBuilder_ = null;
              menuchild_ = other.menuchild_;
              bitField0_ = (bitField0_ & ~0x00000010);
              menuchildBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMenuchildFieldBuilder() : null;
            } else {
              menuchildBuilder_.addAllMessages(other.menuchild_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        role.MenuOuterClass.MenuItem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (role.MenuOuterClass.MenuItem) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object menuparent_ = "";
      /**
       * <code>string menuparent = 1;</code>
       */
      public java.lang.String getMenuparent() {
        java.lang.Object ref = menuparent_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          menuparent_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string menuparent = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMenuparentBytes() {
        java.lang.Object ref = menuparent_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          menuparent_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string menuparent = 1;</code>
       */
      public Builder setMenuparent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        menuparent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string menuparent = 1;</code>
       */
      public Builder clearMenuparent() {
        
        menuparent_ = getDefaultInstance().getMenuparent();
        onChanged();
        return this;
      }
      /**
       * <code>string menuparent = 1;</code>
       */
      public Builder setMenuparentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        menuparent_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object menuname_ = "";
      /**
       * <code>string menuname = 2;</code>
       */
      public java.lang.String getMenuname() {
        java.lang.Object ref = menuname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          menuname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string menuname = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMenunameBytes() {
        java.lang.Object ref = menuname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          menuname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string menuname = 2;</code>
       */
      public Builder setMenuname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        menuname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string menuname = 2;</code>
       */
      public Builder clearMenuname() {
        
        menuname_ = getDefaultInstance().getMenuname();
        onChanged();
        return this;
      }
      /**
       * <code>string menuname = 2;</code>
       */
      public Builder setMenunameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        menuname_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object menucode_ = "";
      /**
       * <code>string menucode = 3;</code>
       */
      public java.lang.String getMenucode() {
        java.lang.Object ref = menucode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          menucode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string menucode = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMenucodeBytes() {
        java.lang.Object ref = menucode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          menucode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string menucode = 3;</code>
       */
      public Builder setMenucode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        menucode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string menucode = 3;</code>
       */
      public Builder clearMenucode() {
        
        menucode_ = getDefaultInstance().getMenucode();
        onChanged();
        return this;
      }
      /**
       * <code>string menucode = 3;</code>
       */
      public Builder setMenucodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        menucode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object seq_ = "";
      /**
       * <code>string seq = 4;</code>
       */
      public java.lang.String getSeq() {
        java.lang.Object ref = seq_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          seq_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string seq = 4;</code>
       */
      public com.google.protobuf.ByteString
          getSeqBytes() {
        java.lang.Object ref = seq_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          seq_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string seq = 4;</code>
       */
      public Builder setSeq(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        seq_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string seq = 4;</code>
       */
      public Builder clearSeq() {
        
        seq_ = getDefaultInstance().getSeq();
        onChanged();
        return this;
      }
      /**
       * <code>string seq = 4;</code>
       */
      public Builder setSeqBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        seq_ = value;
        onChanged();
        return this;
      }

      private java.util.List<role.MenuOuterClass.MenuItem> menuchild_ =
        java.util.Collections.emptyList();
      private void ensureMenuchildIsMutable() {
        if (!((bitField0_ & 0x00000010) != 0)) {
          menuchild_ = new java.util.ArrayList<role.MenuOuterClass.MenuItem>(menuchild_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          role.MenuOuterClass.MenuItem, role.MenuOuterClass.MenuItem.Builder, role.MenuOuterClass.MenuItemOrBuilder> menuchildBuilder_;

      /**
       * <code>repeated .role.MenuItem menuchild = 5;</code>
       */
      public java.util.List<role.MenuOuterClass.MenuItem> getMenuchildList() {
        if (menuchildBuilder_ == null) {
          return java.util.Collections.unmodifiableList(menuchild_);
        } else {
          return menuchildBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .role.MenuItem menuchild = 5;</code>
       */
      public int getMenuchildCount() {
        if (menuchildBuilder_ == null) {
          return menuchild_.size();
        } else {
          return menuchildBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .role.MenuItem menuchild = 5;</code>
       */
      public role.MenuOuterClass.MenuItem getMenuchild(int index) {
        if (menuchildBuilder_ == null) {
          return menuchild_.get(index);
        } else {
          return menuchildBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .role.MenuItem menuchild = 5;</code>
       */
      public Builder setMenuchild(
          int index, role.MenuOuterClass.MenuItem value) {
        if (menuchildBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMenuchildIsMutable();
          menuchild_.set(index, value);
          onChanged();
        } else {
          menuchildBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .role.MenuItem menuchild = 5;</code>
       */
      public Builder setMenuchild(
          int index, role.MenuOuterClass.MenuItem.Builder builderForValue) {
        if (menuchildBuilder_ == null) {
          ensureMenuchildIsMutable();
          menuchild_.set(index, builderForValue.build());
          onChanged();
        } else {
          menuchildBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .role.MenuItem menuchild = 5;</code>
       */
      public Builder addMenuchild(role.MenuOuterClass.MenuItem value) {
        if (menuchildBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMenuchildIsMutable();
          menuchild_.add(value);
          onChanged();
        } else {
          menuchildBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .role.MenuItem menuchild = 5;</code>
       */
      public Builder addMenuchild(
          int index, role.MenuOuterClass.MenuItem value) {
        if (menuchildBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMenuchildIsMutable();
          menuchild_.add(index, value);
          onChanged();
        } else {
          menuchildBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .role.MenuItem menuchild = 5;</code>
       */
      public Builder addMenuchild(
          role.MenuOuterClass.MenuItem.Builder builderForValue) {
        if (menuchildBuilder_ == null) {
          ensureMenuchildIsMutable();
          menuchild_.add(builderForValue.build());
          onChanged();
        } else {
          menuchildBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .role.MenuItem menuchild = 5;</code>
       */
      public Builder addMenuchild(
          int index, role.MenuOuterClass.MenuItem.Builder builderForValue) {
        if (menuchildBuilder_ == null) {
          ensureMenuchildIsMutable();
          menuchild_.add(index, builderForValue.build());
          onChanged();
        } else {
          menuchildBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .role.MenuItem menuchild = 5;</code>
       */
      public Builder addAllMenuchild(
          java.lang.Iterable<? extends role.MenuOuterClass.MenuItem> values) {
        if (menuchildBuilder_ == null) {
          ensureMenuchildIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, menuchild_);
          onChanged();
        } else {
          menuchildBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .role.MenuItem menuchild = 5;</code>
       */
      public Builder clearMenuchild() {
        if (menuchildBuilder_ == null) {
          menuchild_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          menuchildBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .role.MenuItem menuchild = 5;</code>
       */
      public Builder removeMenuchild(int index) {
        if (menuchildBuilder_ == null) {
          ensureMenuchildIsMutable();
          menuchild_.remove(index);
          onChanged();
        } else {
          menuchildBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .role.MenuItem menuchild = 5;</code>
       */
      public role.MenuOuterClass.MenuItem.Builder getMenuchildBuilder(
          int index) {
        return getMenuchildFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .role.MenuItem menuchild = 5;</code>
       */
      public role.MenuOuterClass.MenuItemOrBuilder getMenuchildOrBuilder(
          int index) {
        if (menuchildBuilder_ == null) {
          return menuchild_.get(index);  } else {
          return menuchildBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .role.MenuItem menuchild = 5;</code>
       */
      public java.util.List<? extends role.MenuOuterClass.MenuItemOrBuilder> 
           getMenuchildOrBuilderList() {
        if (menuchildBuilder_ != null) {
          return menuchildBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(menuchild_);
        }
      }
      /**
       * <code>repeated .role.MenuItem menuchild = 5;</code>
       */
      public role.MenuOuterClass.MenuItem.Builder addMenuchildBuilder() {
        return getMenuchildFieldBuilder().addBuilder(
            role.MenuOuterClass.MenuItem.getDefaultInstance());
      }
      /**
       * <code>repeated .role.MenuItem menuchild = 5;</code>
       */
      public role.MenuOuterClass.MenuItem.Builder addMenuchildBuilder(
          int index) {
        return getMenuchildFieldBuilder().addBuilder(
            index, role.MenuOuterClass.MenuItem.getDefaultInstance());
      }
      /**
       * <code>repeated .role.MenuItem menuchild = 5;</code>
       */
      public java.util.List<role.MenuOuterClass.MenuItem.Builder> 
           getMenuchildBuilderList() {
        return getMenuchildFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          role.MenuOuterClass.MenuItem, role.MenuOuterClass.MenuItem.Builder, role.MenuOuterClass.MenuItemOrBuilder> 
          getMenuchildFieldBuilder() {
        if (menuchildBuilder_ == null) {
          menuchildBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              role.MenuOuterClass.MenuItem, role.MenuOuterClass.MenuItem.Builder, role.MenuOuterClass.MenuItemOrBuilder>(
                  menuchild_,
                  ((bitField0_ & 0x00000010) != 0),
                  getParentForChildren(),
                  isClean());
          menuchild_ = null;
        }
        return menuchildBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:role.MenuItem)
    }

    // @@protoc_insertion_point(class_scope:role.MenuItem)
    private static final role.MenuOuterClass.MenuItem DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new role.MenuOuterClass.MenuItem();
    }

    public static role.MenuOuterClass.MenuItem getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MenuItem>
        PARSER = new com.google.protobuf.AbstractParser<MenuItem>() {
      @java.lang.Override
      public MenuItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MenuItem(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MenuItem> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MenuItem> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public role.MenuOuterClass.MenuItem getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_role_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_role_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_role_Reply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_role_Reply_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_role_MenuItem_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_role_MenuItem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nmenu.proto\022\004role\"\025\n\007Request\022\n\n\002id\030\001 \001(" +
      "\t\"5\n\005Reply\022\n\n\002id\030\001 \001(\t\022 \n\010menuItem\030\005 \001(\013" +
      "2\016.role.MenuItem\"r\n\010MenuItem\022\022\n\nmenupare" +
      "nt\030\001 \001(\t\022\020\n\010menuname\030\002 \001(\t\022\020\n\010menucode\030\003" +
      " \001(\t\022\013\n\003seq\030\004 \001(\t\022!\n\tmenuchild\030\005 \003(\0132\016.r" +
      "ole.MenuItem2,\n\004Menu\022$\n\004Menu\022\r.role.Requ" +
      "est\032\013.role.Reply\"\000B\006\242\002\003HLWb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_role_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_role_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_role_Request_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_role_Reply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_role_Reply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_role_Reply_descriptor,
        new java.lang.String[] { "Id", "MenuItem", });
    internal_static_role_MenuItem_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_role_MenuItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_role_MenuItem_descriptor,
        new java.lang.String[] { "Menuparent", "Menuname", "Menucode", "Seq", "Menuchild", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
